replicaCount: 2

image:
  tag: 1.0.0
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
containerPort: 80

resources:
  limits:
    cpu: 128m
    memory: 256Mi
  requests:
    cpu: 128m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
  minReplicas: 2
  maxReplicas: 4
  targetAverageUtilization: 99

canary:
  primaryHostname: app-primary.flagger
  canaryHostname: app-canary.flagger
  ttl: 1
  progressDeadlineSeconds: 600 # default 600s
  meshName: flagger
  canaryAnalysis:
    interval: 10s # default 60s
    threshold: 10
    maxWeight: 50
    stepWeight: 10
    metrics:
      requestSuccessRate:
        threshold: 99
        interval: 1m
  loadTest:
    enabled: true
    url: http://flagger-loadtester.flagger/
    timeout: 5s
    cmd: hey -z 1m -q 100 -c 100 http://app.flagger/