apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: {{ include "app.fullname" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" . }}
  progressDeadlineSeconds: {{ .Values.canary.progressDeadlineSeconds }}
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: {{ include "app.fullname" . }}
  service:
    port: {{ .Values.containerPort }}
    meshName: {{ .Values.canary.meshName }}
  canaryAnalysis:
    interval: {{ .Values.canary.canaryAnalysis.interval }}
    threshold: {{ .Values.canary.canaryAnalysis.threshold }}
    maxWeight: {{ .Values.canary.canaryAnalysis.maxWeight }}
    stepWeight: {{ .Values.canary.canaryAnalysis.stepWeight }}
    metrics:
      - name: request-success-rate
        threshold: {{ .Values.canary.canaryAnalysis.metrics.requestSuccessRate.threshold }}
        interval: {{ .Values.canary.canaryAnalysis.metrics.requestSuccessRate.interval }}
    {{- if .Values.canary.loadTest.enabled }}
    webhooks:
      - name: load-test
        url: {{ .Values.canary.loadTest.url }}
        timeout: {{ .Values.canary.loadTest.timeout }}
        metadata:
          cmd: {{ .Values.canary.loadTest.cmd }}
    {{- end }}