---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: flagger
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: api
  chart:
    git: git@github.com:aonz/app-mesh-flux-flagger.git
    ref: master
    path: flux/charts/api
  values:
    image:
      repository: 685329721066.dkr.ecr.ap-southeast-1.amazonaws.com/app-mesh-flux-flagger-api
      tag: 1.0.0
