apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-controller
  namespace: appmesh-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: appmesh-controller
  chart:
    repository: https://aws.github.io/eks-charts
    name: appmesh-controller
    version: 0.4.0
