apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: aws-appmesh
  namespace: appmesh-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: aws-appmesh
  chart:
    git: git@github.com:aonz/app-mesh-flux-flagger.git
    ref: master
    path: flux/charts/aws-appmesh
  values:
    aws-appmesh-inject:
      meshName: flagger
      webHookImage:
        repository: quay.io/aonz/aws-app-mesh-inject
        tag: v0.1.5
      envoyImage: 
        tag: v1.9.1.0-prod
      initImage:
        tag: v2