apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger-loadtester
  namespace: flagger
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flagger-loadtester
  chart:
    repository: https://flagger.app
    name: loadtester
    version: 0.12.1
  values:
    meshName: flagger
    backends:
      - backend.flagger
