apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.17.0
  valuesFrom:
  - configMapKeyRef:
      name: flagger
      key: values.yaml 
      optional: false
  values:
    crd:
      create: false
    meshProvider: appmesh
    metricsServer: http://appmesh-prometheus:9090
    slack:
      channel: flagger
      user: flagger
