apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.23.0
  valuesFrom:
    - configMapKeyRef:
        name: flagger
  values:
    meshProvider: appmesh
    metricsServer: http://appmesh-prometheus:9090
    slack:
      channel: flagger
      user: flagger
