apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: appmesh-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: metrics-server
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metrics-server
    version: 2.8.2