apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: flagger
  namespace: app-mesh-demo
spec:
  namespaceSelector:
    matchLabels:
      name: app-mesh-demo
  egressFilter:
    type: ALLOW_ALL
