# apiVersion: appmesh.k8s.aws/v1beta2
# kind: VirtualService
# metadata:
#   name: {{ include "app.fullname" . }}
#   labels:
#     app: {{ include "app.fullname" . }}
# spec:
#   awsName: api.flagger
#   provider:
#     virtualRouter:
#       virtualRouterRef:
#         name: api
