# apiVersion: appmesh.k8s.aws/v1beta2
# kind: VirtualService
# metadata:
#   name: {{ include "app.fullname" . }}
#   labels:
#     app: {{ include "app.fullname" . }}
# spec:
#   awsName: api.flagger
#   listeners:
#     - portMapping:
#         port: {{ .Values.containerPort }}
#         protocol: http
#   routes:
#     - name: api
#       http:
#         match:
#           prefix: /
#         action:
#           weightedTargets:
#             - virtualNodeName: api
#               weight: 100
#         retryPolicy:
#           httpRetryEvents:
#             - gateway-error
#             - client-error
#             - stream-error
#           maxRetries: 3
#           perRetryTimeout:
#             unit: ms
#             value: 1000
